version: '3.8'

services:
  go-echo-server:
    build:
      context: ./go-echo-server
      dockerfile: Dockerfile
    volumes:
      - ./go-echo-server:/go-echo-server
    working_dir: /go-echo-server
    ports:
      - "1323:1323"
    networks:
      - app-network
    command: sh -c 'go mod tidy && air'

  go-gin-server:
    build:
      context: ./go-gin-server
      dockerfile: Dockerfile
    volumes:
      - ./go-gin-server:/go-gin-server
    working_dir: /go-gin-server
    ports:
      - "8080:8080"
    networks:
      - app-network
    command: sh -c 'go mod tidy && air'

networks:
  app-network:
    driver: bridge
