FROM golang:1.22

WORKDIR /usr/src/app

RUN go install github.com/cosmtrek/air@latest

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

EXPOSE 8080
RUN go mod tidy
CMD ["air"]
